version: '3.0'
services:
  nestapp:
    container_name: AUTHAPP
    image: ghanem/auth-app
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=mysql
      - DB_USER=ghanem
      - DB_PASSWORD=123
      - DB_NAME=db
      - DB_PORT=3306
      - DB_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ghanem'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123'
      
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
# Names our volume
volumes:
  db: